### ISSUE TITLE
Incorrect latest chapter display

### ISSUE THREAD

**Issue by Weefsat** [doutatsu/kenmei#101] opened 2019-11-24 12:36 UTC
Chuukan Kanriroku Tonegawa doesn't display chapters. The reason is that the latest upload was some sort of chapter 0 oneshot?

https://mangadex.org/manga/15691
![Untitled](https://user-images.githubusercontent.com/39443093/69494719-317c6600-0ebf-11ea-812d-e316c8442e3c.png)

**Comment by doutatsu** [comment] 2019-11-24 13:30
@Weefsat Thanks, that's another edgecase that I haven't seen before, its because the Oneshot has a volume assigned to it, but no chapter. I assume if there is a volume, its not going to be a oneshot, but this is a bug, as my code should have still not put the chapter of nothing as the latest.

I've confirmed there are 2 more (out of 4000 series) that I have the same issue. Looking at MangaDex, I think they also not correctly sorting these 😂I should fix this today, I think my algorithm just need a bit of tweaking

**Comment by doutatsu** [comment] 2019-11-24 15:34
Urgh, I've tested my code and it has no issues. I then went and tried updating those series again and all of them show correct chapters now. I have no way of knowing in what shape they were when I first grabbed them, but they must have had some incorrect data, which then got fixed... 

I need to add more logging, so I can go back and find out the issues a chapter might have had, even after it has been fixed on MangaDex. For now, closing this 👌🏻I've also got on the backlog a more proactive "Report chapter" functionality, that would make this a bit easier to manage for me, when its just some data issue

**Closed by doutatsu** 2019-11-24 15:34 UTC
Labels: bug
